# Generated by Django 5.2.9 on 2026-01-03 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('perenual_id', models.IntegerField(blank=True, help_text='Perenual API plant ID', null=True, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('scientific_name', models.CharField(blank=True, max_length=200, null=True)),
                ('common_names', models.TextField(blank=True, help_text='Comma-separated alternative names', null=True)),
                ('description', models.TextField()),
                ('care_level', models.CharField(choices=[('Easy', 'Easy'), ('Medium', 'Medium'), ('Hard', 'Hard')], default='Medium', max_length=20)),
                ('water_frequency_days', models.IntegerField(help_text='How often to water (in days)')),
                ('sunlight', models.CharField(choices=[('Full Sun', 'Full Sun'), ('Partial Sun', 'Partial Sun'), ('Indirect Light', 'Indirect Light'), ('Low Light', 'Low Light'), ('Shade', 'Shade')], max_length=50)),
                ('temperature_min', models.IntegerField(help_text='Minimum temperature in Celsius')),
                ('temperature_max', models.IntegerField(help_text='Maximum temperature in Celsius')),
                ('humidity_level', models.CharField(blank=True, help_text='e.g., High, Medium, Low', max_length=100, null=True)),
                ('category', models.CharField(choices=[('Flowering', 'Flowering'), ('Foliage', 'Foliage'), ('Succulent', 'Succulent'), ('Cactus', 'Cactus'), ('Herb', 'Herb'), ('Vegetable', 'Vegetable'), ('Fruit', 'Fruit'), ('Tree', 'Tree'), ('Vine', 'Vine'), ('Fern', 'Fern')], max_length=50)),
                ('image_url', models.URLField(blank=True, null=True)),
                ('care_tips', models.TextField(blank=True, help_text='JSON format: tips for caring', null=True)),
                ('is_popular', models.BooleanField(default=False)),
                ('is_beginner_friendly', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Plant',
                'verbose_name_plural': 'Plants',
                'ordering': ['name'],
            },
        ),
    ]
