# Generated by Django 5.2.9 on 2026-01-04 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plant',
            name='perenual_id',
        ),
        migrations.AddField(
            model_name='plant',
            name='trefle_id',
            field=models.IntegerField(blank=True, help_text='Trefle API plant ID', null=True, unique=True),
        ),
    ]
