# Generated by Django 5.2.9 on 2026-01-04 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0002_remove_plant_perenual_id_plant_trefle_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='name_urdu',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
