# Generated by Django 5.2.9 on 2026-01-04 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0003_plant_name_urdu'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='description_urdu',
            field=models.TextField(blank=True, null=True),
        ),
    ]
